### ISSUE TITLE
[Feature]: run r cmd check more often?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/asar#258]
### Is your feature request related to a problem? Please describe.

Hi! I just noticed that the [r cmd check github action](https://github.com/nmfs-ost/asar/blob/main/.github/workflows/call-r-cmd-check.yml) only runs on pushes to main or pull requests to main. 

### Describe the solution you would like.

I wonder if maybe the build triggers should be modified so it runs more often, perhaps on pushes to main or dev, or prs to main or dev? Maybe a manual run option (workflow_dispatch) would also be helpful, too. Here's what the build trigger should be modified to:

```yml
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
```

### Describe alternatives you have considered

leave as is.
